fix texture coordinate order and face vertex indices
MovingBlocks/BlenderAddon pull request #6
Opened 2021-03-21 09:36 UTC by antag99

According to https://docs.blender.org/api/current/bpy.types.Mesh.html, Mesh.loops, Mesh.uv_layers Mesh.vertex_colors are all aligned so the same polygon loop indices can be used to find the UV’s and vertex colors as with as the vertices. (Which is a somewhat confusing sentence to be honest.)

I have updated the export script to use the loops[i].vertex_index variable, as well as using this to ensure the list of UV coordinates are aligned with the list of vertices. This corrects an issue I had with exporting a simple mesh to the block shape format, see test module https://github.com/antag99/ShapeTestModule. The blender file under assets/shapes did not export correctly before this fix, but exported correctly afterwards. To test:

- Export assets/shapes/TestBlockShape.blend without the patch
- Create a world with ShapeTestModule enabled
- F1, give ShapeTestModule:TestBlock
- UV coordinates should be all messed up
- Repeat with the patch applied, UV coordinates should be in order

Blender version I use is 2.92.

An alternative option would be to reorder the vertices to match loops instead.

2021-03-23 03:58 UTC, keturn commented
This is the sort of thing that feels like it could benefit from a unit test.

Does this repo have unit tests? _Could_ it? Typically they're not hard to add in Python, but I don't know anything about the world of blender addons, whether there is something that would make the code under test not run unless it's executed by the Blender environment.

2021-03-23 18:52 UTC, antag99 commented
There are solutions to running unit tests in a Blender environment, for example [pytest-blender](https://pypi.org/project/pytest-blender/). I think this tool would also benefit from a bit of documentation (and a license!).

2021-03-27 18:43 UTC, skaldarnar commented
Just added a LICENSE with Apache v2 (as for the other projects) - thanks for noticing!

2021-03-30 02:27 UTC, pollend requested changes

2021-03-30 02:27 UTC, pollend commented on shapes_operator/tera_shape_export.py
> +        result['texcoords'] = [NoIndent([0,0])for _ in range(0, len(mesh.loops))]
```suggestion
        result['texcoords'] = [NoIndent([0,0]) for _ in range(0, len(mesh.loops))]
```

2021-03-30 02:27 UTC, pollend commented
didn't test this but this looks good to me.

2021-04-03 20:38 UTC, pollend commented
just compared the two blender files and this look good :D

2021-04-03 20:38 UTC, merged